/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_hwrec_JavaNativeCalculator.h"
/* Header for class com_hwrec_JavaNativeCalculator */

#ifndef _Included_com_hwrec_JavaNativeCalculator
#define _Included_com_hwrec_JavaNativeCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hwrec_JavaNativeCalculator
 * Method:    distance
 * Signature: (Lscala/collection/immutable/Seq;Lscala/collection/immutable/Seq;)D
 */
JNIEXPORT jdouble JNICALL Java_com_hwrec_JavaNativeCalculator_distance
  (JNIEnv *, jobject, jobject, jobject){

  jdouble res = 10.5
  return res

  }

#ifdef __cplusplus
}
#endif
#endif
