/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hwrec_JavaNativeCalculator */

#ifndef _Included_com_hwrec_JavaNativeCalculator
#define _Included_com_hwrec_JavaNativeCalculator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hwrec_JavaNativeCalculator
 * Method:    distance
 * Signature: ([B[B)D
 */
JNIEXPORT jdouble JNICALL Java_com_hwrec_JavaNativeCalculator_distance
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
